### ISSUE TITLE
Points inconsistent

### ISSUE THREAD

**Issue by Hypn0tyk** [SamHourai/WIFFXIV-Public#1]
**Describe the bug**

I have gotten full credit by being within the green circle but on the very edge and low scores by being pretty close to center (example low score https://i.imgur.com/ti6XrVd.png)

**Comment by SamHourai** [comment]
Hmmm, it's very weird, I just tried it myself, I got the maximum score on this point ...
I'll investigate, thanks for reporting!

**Comment by SamHourai** [comment]
The scoring system will be redeveloped and improved, to see if the bug persists.
