### ISSUE TITLE
2 lil things I noticed

### ISSUE THREAD

**Issue by GrumpyAna** [SamHourai/WIFFXIV-Public#4]
Hi !
Just played 2 or 3 games and noticed that on the Limsa Lominsa guess, your location shows on the map :3
Well it's a cool way to get points though !

Also, once you registered your score with a nickname, you cannot use this name again. That's sad when you had 2300 points on first, then score a 3900 on the second :(

Hope you'll find these helpfull !
Also, that's an amazing idea of a game, thank you !
Ana

**Comment by LackovicTom** [comment]
Hello, yes this has been mentioned many times already, I am currently working on it to fix this, and I'm looking for a solution for the nickname. Thank you so much for your feedback!

**Comment by SamHourai** [comment]
Hello, yes this has been mentioned many times already, I am currently working on it to fix this, and I'm looking for a solution for the nickname. Thank you so much for your feedback!
